'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WarGames.Resource1", GetType(Resource1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Ace_Clubs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ace Clubs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Ace_Diamonds() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ace Diamonds", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Ace_Hearts() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ace Hearts", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Ace_Spades() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ace Spades", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Eight_Clubs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Eight Clubs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Eight_Diamonds() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Eight Diamonds", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Eight_Hearts() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Eight Hearts", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Eight_Spades() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Eight Spades", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Five_Clubs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Five Clubs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Five_Diamonds() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Five Diamonds", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Five_Hearts() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Five Hearts", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Five_Spades() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Five Spades", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Four_Clubs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Four Clubs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Four_Diamonds() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Four Diamonds", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Four_Hearts() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Four Hearts", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Four_Spades() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Four Spades", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Joker_Clubs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Joker Clubs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Joker_Diamonds() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Joker Diamonds", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Joker_Hearts() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Joker Hearts", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Joker_Spades() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Joker Spades", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property King_Clubs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("King Clubs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property King_Diamonds() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("King Diamonds", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property King_Hearts() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("King Hearts", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property King_Spades() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("King Spades", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Nine_Clubs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Nine Clubs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Nine_Diamonds() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Nine Diamonds", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Nine_Hearts() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Nine Hearts", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Nine_Spades() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Nine Spades", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Queen_Clubs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Queen Clubs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Queen_Diamonds() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Queen Diamonds", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Queen_Hearts() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Queen Hearts", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Queen_Spades() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Queen Spades", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Seven_Clubs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Seven Clubs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Seven_Diamonds() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Seven Diamonds", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Seven_Hearts() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Seven Hearts", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Seven_Spades() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Seven Spades", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Six_Clubs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Six Clubs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Six_Diamonds() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Six Diamonds", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Six_Hearts() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Six Hearts", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Six_Spades() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Six Spades", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Ten_Clubs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ten Clubs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Ten_Diamonds() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ten Diamonds", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Ten_Hearts() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ten Hearts", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Ten_Spades() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ten Spades", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Three_Clubs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Three Clubs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Three_Diamonds() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Three Diamonds", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Three_Hearts() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Three Hearts", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Three_Spades() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Three Spades", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Two_Clubs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Two Clubs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Two_Diamonds() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Two Diamonds", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Two_Hearts() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Two Hearts", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property Two_Spades() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Two Spades", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Class
End Namespace
